package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("as_emp", "id", AsEmp.class);
		arp.addMapping("ligent_action", "actionID", LigentAction.class);
		arp.addMapping("ligent_action_role", "id", LigentActionRole.class);
		arp.addMapping("ligent_dep", "depID", LigentDep.class);
		arp.addMapping("ligent_menu", "menuID", LigentMenu.class);
		arp.addMapping("ligent_menu_copy", "menuID", LigentMenuCopy.class);
		arp.addMapping("ligent_org", "orgID", LigentOrg.class);
		arp.addMapping("ligent_role", "roleID", LigentRole.class);
		arp.addMapping("ligent_role_menu", "id", LigentRoleMenu.class);
		arp.addMapping("ligent_user", "userID", LigentUser.class);
		arp.addMapping("ligent_user_dep", "id", LigentUserDep.class);
		arp.addMapping("ligent_user_org", "id", LigentUserOrg.class);
		arp.addMapping("ligent_user_role", "id", LigentUserRole.class);
		arp.addMapping("mx_alert", "almID", MxAlert.class);
		arp.addMapping("mx_apilog", "logID", MxApilog.class);
		arp.addMapping("mx_apilog_logerror", "logID", MxApilogLogerror.class);
		arp.addMapping("mx_apiurl", "ID", MxApiurl.class);
		arp.addMapping("mx_area", "areaID", MxArea.class);
		arp.addMapping("mx_area_user", "id", MxAreaUser.class);
		arp.addMapping("mx_citys", "cityID", MxCitys.class);
		arp.addMapping("mx_client", "clientID", MxClient.class);
		arp.addMapping("mx_delog", "devID", MxDelog.class);
		arp.addMapping("mx_device", "devID", MxDevice.class);
		arp.addMapping("mx_device_instrument", "id", MxDeviceInstrument.class);
		arp.addMapping("mx_device_log", "mdlID", MxDeviceLog.class);
		arp.addMapping("mx_devicelog2", "idevID", MxDevicelog2.class);
		arp.addMapping("mx_devicelogbackup_2015", "idevID", MxDevicelogbackup2015.class);
		arp.addMapping("mx_emergency", "id", MxEmergency.class);
		arp.addMapping("mx_field", "fieldID", MxField.class);
		arp.addMapping("mx_filiale", "fID", MxFiliale.class);
		arp.addMapping("mx_ilog_lastdayperday", "ID", MxIlogLastdayperday.class);
		arp.addMapping("mx_ilog_lastdaypermonth", "ID", MxIlogLastdaypermonth.class);
		arp.addMapping("mx_ilog_lastdaypertime", "milID", MxIlogLastdaypertime.class);
		arp.addMapping("mx_ilog_lastdayresult", "ID", MxIlogLastdayresult.class);
		arp.addMapping("mx_ilog_month", "ID", MxIlogMonth.class);
		arp.addMapping("mx_ilog_month_2017", "ID", MxIlogMonth2017.class);
		arp.addMapping("mx_instrument", "insID", MxInstrument.class);
		arp.addMapping("mx_instrumentlog", "ilogID", MxInstrumentlog.class);
		arp.addMapping("mx_instrumentlog_2015", "ilogID", MxInstrumentlog2015.class);
		arp.addMapping("mx_instrumentlog_2016", "ilogID", MxInstrumentlog2016.class);
		arp.addMapping("mx_instype", "typeID", MxInstype.class);
		arp.addMapping("mx_instype_field", "id", MxInstypeField.class);
		arp.addMapping("mx_log", "id", MxLog.class);
		arp.addMapping("mx_menu", "menuId", MxMenu.class);
		arp.addMapping("mx_msg", "msgID", MxMsg.class);
		arp.addMapping("mx_mydelog", "id", MxMydelog.class);
		arp.addMapping("mx_point", "pointID", MxPoint.class);
		arp.addMapping("mx_present", "id", MxPresent.class);
		arp.addMapping("mx_pros", "proID", MxPros.class);
		arp.addMapping("mx_ptype", "pID", MxPtype.class);
		arp.addMapping("mx_role", "roleId", MxRole.class);
		arp.addMapping("mx_role_menu", "rmId", MxRoleMenu.class);
		arp.addMapping("mx_site", "siteID", MxSite.class);
		arp.addMapping("mx_site_nofound", "foID", MxSiteNofound.class);
		arp.addMapping("mx_unit", "unitID", MxUnit.class);
		arp.addMapping("mx_userlog", "ulogID", MxUserlog.class);
		arp.addMapping("mx_volume", "volID", MxVolume.class);
		arp.addMapping("mx_warn", "warnId", MxWarn.class);
		arp.addMapping("mx_warntype", "warnTypeId", MxWarntype.class);
		arp.addMapping("mx_warnuser", "userWarnId", MxWarnuser.class);
	}
}

