package model;

import model.base.BaseAsEmp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsEmp extends BaseAsEmp<AsEmp> {
	public static final AsEmp dao = new AsEmp().dao();
}
