package model;

import model.base.BaseLigentUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentUser extends BaseLigentUser<LigentUser> {
	public static final LigentUser dao = new LigentUser().dao();
}
