package model;

import model.base.BaseLigentMenuCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentMenuCopy extends BaseLigentMenuCopy<LigentMenuCopy> {
	public static final LigentMenuCopy dao = new LigentMenuCopy().dao();
}
