package model;

import model.base.BaseLigentMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentMenu extends BaseLigentMenu<LigentMenu> {
	public static final LigentMenu dao = new LigentMenu().dao();
}
