package model;

import model.base.BaseLigentOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentOrg extends BaseLigentOrg<LigentOrg> {
	public static final LigentOrg dao = new LigentOrg().dao();
}
