package model;

import model.base.BaseLigentUserDep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentUserDep extends BaseLigentUserDep<LigentUserDep> {
	public static final LigentUserDep dao = new LigentUserDep().dao();
}
