package model;

import model.base.BaseLigentDep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentDep extends BaseLigentDep<LigentDep> {
	public static final LigentDep dao = new LigentDep().dao();
}
