package model;

import model.base.BaseLigentUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentUserRole extends BaseLigentUserRole<LigentUserRole> {
	public static final LigentUserRole dao = new LigentUserRole().dao();
}
