package model;

import model.base.BaseLigentRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentRoleMenu extends BaseLigentRoleMenu<LigentRoleMenu> {
	public static final LigentRoleMenu dao = new LigentRoleMenu().dao();
}
