package model;

import model.base.BaseLigentUserOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentUserOrg extends BaseLigentUserOrg<LigentUserOrg> {
	public static final LigentUserOrg dao = new LigentUserOrg().dao();
}
