package model;

import model.base.BaseLigentRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentRole extends BaseLigentRole<LigentRole> {
	public static final LigentRole dao = new LigentRole().dao();
}
