package model;

import model.base.BaseLigentActionRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentActionRole extends BaseLigentActionRole<LigentActionRole> {
	public static final LigentActionRole dao = new LigentActionRole().dao();
}
