package model;

import model.base.BaseLigentAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LigentAction extends BaseLigentAction<LigentAction> {
	public static final LigentAction dao = new LigentAction().dao();
}
