package model;

import model.base.BaseMxAlert;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxAlert extends BaseMxAlert<MxAlert> {
	public static final MxAlert dao = new MxAlert().dao();
}
