package model;

import model.base.BaseMxApiurl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxApiurl extends BaseMxApiurl<MxApiurl> {
	public static final MxApiurl dao = new MxApiurl().dao();
}
