package model;

import model.base.BaseMxApilogLogerror;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxApilogLogerror extends BaseMxApilogLogerror<MxApilogLogerror> {
	public static final MxApilogLogerror dao = new MxApilogLogerror().dao();
}
