package model;

import model.base.BaseMxApilog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxApilog extends BaseMxApilog<MxApilog> {
	public static final MxApilog dao = new MxApilog().dao();
}
