package model;

import model.base.BaseMxAreaUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxAreaUser extends BaseMxAreaUser<MxAreaUser> {
	public static final MxAreaUser dao = new MxAreaUser().dao();
}
