package model;

import model.base.BaseMxArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxArea extends BaseMxArea<MxArea> {
	public static final MxArea dao = new MxArea().dao();
}
