package model;

import model.base.BaseMxCitys;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxCitys extends BaseMxCitys<MxCitys> {
	public static final MxCitys dao = new MxCitys().dao();
}
