package model;

import model.base.BaseMxClient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxClient extends BaseMxClient<MxClient> {
	public static final MxClient dao = new MxClient().dao();
}
