package model;

import model.base.BaseMxDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxDevice extends BaseMxDevice<MxDevice> {
	public static final MxDevice dao = new MxDevice().dao();
}
