package model;

import model.base.BaseMxDeviceLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxDeviceLog extends BaseMxDeviceLog<MxDeviceLog> {
	public static final MxDeviceLog dao = new MxDeviceLog().dao();
}
