package model;

import model.base.BaseMxDeviceInstrument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxDeviceInstrument extends BaseMxDeviceInstrument<MxDeviceInstrument> {
	public static final MxDeviceInstrument dao = new MxDeviceInstrument().dao();
}
