package model;

import model.base.BaseMxDelog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxDelog extends BaseMxDelog<MxDelog> {
	public static final MxDelog dao = new MxDelog().dao();
}
