package model;

import model.base.BaseMxDevicelogbackup2015;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxDevicelogbackup2015 extends BaseMxDevicelogbackup2015<MxDevicelogbackup2015> {
	public static final MxDevicelogbackup2015 dao = new MxDevicelogbackup2015().dao();
}
