package model;

import model.base.BaseMxDevicelog2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxDevicelog2 extends BaseMxDevicelog2<MxDevicelog2> {
	public static final MxDevicelog2 dao = new MxDevicelog2().dao();
}
