package model;

import model.base.BaseMxEmergency;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxEmergency extends BaseMxEmergency<MxEmergency> {
	public static final MxEmergency dao = new MxEmergency().dao();
}
