package model;

import model.base.BaseMxFiliale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxFiliale extends BaseMxFiliale<MxFiliale> {
	public static final MxFiliale dao = new MxFiliale().dao();
}
