package model;

import model.base.BaseMxField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxField extends BaseMxField<MxField> {
	public static final MxField dao = new MxField().dao();
}
