package model;

import model.base.BaseMxIlogMonth2017;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxIlogMonth2017 extends BaseMxIlogMonth2017<MxIlogMonth2017> {
	public static final MxIlogMonth2017 dao = new MxIlogMonth2017().dao();
}
