package model;

import model.base.BaseMxIlogLastdayperday;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxIlogLastdayperday extends BaseMxIlogLastdayperday<MxIlogLastdayperday> {
	public static final MxIlogLastdayperday dao = new MxIlogLastdayperday().dao();
}
