package model;

import model.base.BaseMxIlogLastdayresult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxIlogLastdayresult extends BaseMxIlogLastdayresult<MxIlogLastdayresult> {
	public static final MxIlogLastdayresult dao = new MxIlogLastdayresult().dao();
}
