package model;

import model.base.BaseMxIlogLastdaypermonth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxIlogLastdaypermonth extends BaseMxIlogLastdaypermonth<MxIlogLastdaypermonth> {
	public static final MxIlogLastdaypermonth dao = new MxIlogLastdaypermonth().dao();
}
