package model;

import model.base.BaseMxIlogLastdaypertime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxIlogLastdaypertime extends BaseMxIlogLastdaypertime<MxIlogLastdaypertime> {
	public static final MxIlogLastdaypertime dao = new MxIlogLastdaypertime().dao();
}
