package model;

import model.base.BaseMxIlogMonth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxIlogMonth extends BaseMxIlogMonth<MxIlogMonth> {
	public static final MxIlogMonth dao = new MxIlogMonth().dao();
}
