package model;

import model.base.BaseMxInstype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxInstype extends BaseMxInstype<MxInstype> {
	public static final MxInstype dao = new MxInstype().dao();
}
