package model;

import model.base.BaseMxInstrument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxInstrument extends BaseMxInstrument<MxInstrument> {
	public static final MxInstrument dao = new MxInstrument().dao();
}
