package model;

import model.base.BaseMxInstrumentlog2016;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxInstrumentlog2016 extends BaseMxInstrumentlog2016<MxInstrumentlog2016> {
	public static final MxInstrumentlog2016 dao = new MxInstrumentlog2016().dao();
}
