package model;

import model.base.BaseMxInstrumentlog2015;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxInstrumentlog2015 extends BaseMxInstrumentlog2015<MxInstrumentlog2015> {
	public static final MxInstrumentlog2015 dao = new MxInstrumentlog2015().dao();
}
