package model;

import model.base.BaseMxInstrumentlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxInstrumentlog extends BaseMxInstrumentlog<MxInstrumentlog> {
	public static final MxInstrumentlog dao = new MxInstrumentlog().dao();
}
