package model;

import model.base.BaseMxInstypeField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxInstypeField extends BaseMxInstypeField<MxInstypeField> {
	public static final MxInstypeField dao = new MxInstypeField().dao();
}
