package model;

import model.base.BaseMxLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxLog extends BaseMxLog<MxLog> {
	public static final MxLog dao = new MxLog().dao();
}
