package model;

import model.base.BaseMxMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxMenu extends BaseMxMenu<MxMenu> {
	public static final MxMenu dao = new MxMenu().dao();
}
