package model;

import model.base.BaseMxMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxMsg extends BaseMxMsg<MxMsg> {
	public static final MxMsg dao = new MxMsg().dao();
}
