package model;

import model.base.BaseMxMydelog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxMydelog extends BaseMxMydelog<MxMydelog> {
	public static final MxMydelog dao = new MxMydelog().dao();
}
