package model;

import model.base.BaseMxPoint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxPoint extends BaseMxPoint<MxPoint> {
	public static final MxPoint dao = new MxPoint().dao();
}
