package model;

import model.base.BaseMxPresent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxPresent extends BaseMxPresent<MxPresent> {
	public static final MxPresent dao = new MxPresent().dao();
}
