package model;

import model.base.BaseMxPros;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxPros extends BaseMxPros<MxPros> {
	public static final MxPros dao = new MxPros().dao();
}
