package model;

import model.base.BaseMxPtype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxPtype extends BaseMxPtype<MxPtype> {
	public static final MxPtype dao = new MxPtype().dao();
}
