package model;

import model.base.BaseMxRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxRoleMenu extends BaseMxRoleMenu<MxRoleMenu> {
	public static final MxRoleMenu dao = new MxRoleMenu().dao();
}
