package model;

import model.base.BaseMxRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxRole extends BaseMxRole<MxRole> {
	public static final MxRole dao = new MxRole().dao();
}
