package model;

import model.base.BaseMxSite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxSite extends BaseMxSite<MxSite> {
	public static final MxSite dao = new MxSite().dao();
}
