package model;

import model.base.BaseMxSiteNofound;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxSiteNofound extends BaseMxSiteNofound<MxSiteNofound> {
	public static final MxSiteNofound dao = new MxSiteNofound().dao();
}
