package model;

import model.base.BaseMxUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxUnit extends BaseMxUnit<MxUnit> {
	public static final MxUnit dao = new MxUnit().dao();
}
