package model;

import model.base.BaseMxUserlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxUserlog extends BaseMxUserlog<MxUserlog> {
	public static final MxUserlog dao = new MxUserlog().dao();
}
