package model;

import model.base.BaseMxVolume;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxVolume extends BaseMxVolume<MxVolume> {
	public static final MxVolume dao = new MxVolume().dao();
}
