package model;

import model.base.BaseMxWarnuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxWarnuser extends BaseMxWarnuser<MxWarnuser> {
	public static final MxWarnuser dao = new MxWarnuser().dao();
}
