package model;

import model.base.BaseMxWarn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxWarn extends BaseMxWarn<MxWarn> {
	public static final MxWarn dao = new MxWarn().dao();
}
