package model;

import model.base.BaseMxWarntype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxWarntype extends BaseMxWarntype<MxWarntype> {
	public static final MxWarntype dao = new MxWarntype().dao();
}
