package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxCitys<M extends BaseMxCitys<M>> extends Model<M> implements IBean {

	public void setCityID(java.lang.Integer cityID) {
		set("cityID", cityID);
	}
	
	public java.lang.Integer getCityID() {
		return getInt("cityID");
	}

	public void setCityName(java.lang.String cityName) {
		set("cityName", cityName);
	}
	
	public java.lang.String getCityName() {
		return getStr("cityName");
	}

	public void setProID(java.lang.Integer proID) {
		set("proID", proID);
	}
	
	public java.lang.Integer getProID() {
		return getInt("proID");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

}
