package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxSiteNofound<M extends BaseMxSiteNofound<M>> extends Model<M> implements IBean {

	public void setFoID(java.lang.Integer foID) {
		set("foID", foID);
	}
	
	public java.lang.Integer getFoID() {
		return getInt("foID");
	}

	public void setSiteNo(java.lang.String siteNo) {
		set("siteNo", siteNo);
	}
	
	public java.lang.String getSiteNo() {
		return getStr("siteNo");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	public java.lang.Integer getNum() {
		return getInt("num");
	}

}
