package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxArea<M extends BaseMxArea<M>> extends Model<M> implements IBean {

	public void setAreaID(java.lang.Integer areaID) {
		set("areaID", areaID);
	}
	
	public java.lang.Integer getAreaID() {
		return getInt("areaID");
	}

	public void setAreaName(java.lang.String areaName) {
		set("areaName", areaName);
	}
	
	public java.lang.String getAreaName() {
		return getStr("areaName");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}
	
	public java.lang.String getKeyword() {
		return getStr("keyword");
	}

	public void setLot(java.lang.Double lot) {
		set("lot", lot);
	}
	
	public java.lang.Double getLot() {
		return getDouble("lot");
	}

	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}
	
	public java.lang.Double getLat() {
		return getDouble("lat");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setAreaStatus(java.lang.Integer areaStatus) {
		set("areaStatus", areaStatus);
	}
	
	public java.lang.Integer getAreaStatus() {
		return getInt("areaStatus");
	}

}
