package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxVolume<M extends BaseMxVolume<M>> extends Model<M> implements IBean {

	public void setVolID(java.lang.Integer volID) {
		set("volID", volID);
	}
	
	public java.lang.Integer getVolID() {
		return getInt("volID");
	}

	public void setVolNum(java.lang.String volNum) {
		set("volNum", volNum);
	}
	
	public java.lang.String getVolNum() {
		return getStr("volNum");
	}

	public void setVolName(java.lang.String volName) {
		set("volName", volName);
	}
	
	public java.lang.String getVolName() {
		return getStr("volName");
	}

	public void setMaximum(java.lang.Integer maximum) {
		set("maximum", maximum);
	}
	
	public java.lang.Integer getMaximum() {
		return getInt("maximum");
	}

}
