package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxUserlog<M extends BaseMxUserlog<M>> extends Model<M> implements IBean {

	public void setUlogID(java.lang.Integer ulogID) {
		set("ulogID", ulogID);
	}
	
	public java.lang.Integer getUlogID() {
		return getInt("ulogID");
	}

	public void setLogName(java.lang.String logName) {
		set("logName", logName);
	}
	
	public java.lang.String getLogName() {
		return getStr("logName");
	}

	public void setLogaction(java.lang.String logaction) {
		set("logaction", logaction);
	}
	
	public java.lang.String getLogaction() {
		return getStr("logaction");
	}

	public void setLogdesc(java.lang.String logdesc) {
		set("logdesc", logdesc);
	}
	
	public java.lang.String getLogdesc() {
		return getStr("logdesc");
	}

	public void setLogtype(java.lang.Integer logtype) {
		set("logtype", logtype);
	}
	
	public java.lang.Integer getLogtype() {
		return getInt("logtype");
	}

	public void setCrtime(java.util.Date crtime) {
		set("crtime", crtime);
	}
	
	public java.util.Date getCrtime() {
		return get("crtime");
	}

}
