package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxDeviceLog<M extends BaseMxDeviceLog<M>> extends Model<M> implements IBean {

	public void setMdlID(java.lang.Integer mdlID) {
		set("mdlID", mdlID);
	}
	
	public java.lang.Integer getMdlID() {
		return getInt("mdlID");
	}

	public void setDevID(java.lang.Integer devID) {
		set("devID", devID);
	}
	
	public java.lang.Integer getDevID() {
		return getInt("devID");
	}

	public void setDevNo(java.lang.String devNo) {
		set("devNo", devNo);
	}
	
	public java.lang.String getDevNo() {
		return getStr("devNo");
	}

	public void setCidLac(java.lang.String cidLac) {
		set("cid_lac", cidLac);
	}
	
	public java.lang.String getCidLac() {
		return getStr("cid_lac");
	}

	public void setDlState(java.lang.Integer dlState) {
		set("dl_state", dlState);
	}
	
	public java.lang.Integer getDlState() {
		return getInt("dl_state");
	}

	public void setFlagtime(java.util.Date flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.util.Date getFlagtime() {
		return get("flagtime");
	}

}
