package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxMenu<M extends BaseMxMenu<M>> extends Model<M> implements IBean {

	public void setMenuId(java.lang.Integer menuId) {
		set("menuId", menuId);
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menuId");
	}

	public void setMenuName(java.lang.String menuName) {
		set("menuName", menuName);
	}
	
	public java.lang.String getMenuName() {
		return getStr("menuName");
	}

	public void setSysId(java.lang.Integer sysId) {
		set("sysId", sysId);
	}
	
	public java.lang.Integer getSysId() {
		return getInt("sysId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setPaths(java.lang.String paths) {
		set("paths", paths);
	}
	
	public java.lang.String getPaths() {
		return getStr("paths");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
