package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxPresent<M extends BaseMxPresent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setTitleImg(java.lang.String titleImg) {
		set("titleImg", titleImg);
	}
	
	public java.lang.String getTitleImg() {
		return getStr("titleImg");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setSing(java.lang.Integer sing) {
		set("sing", sing);
	}
	
	public java.lang.Integer getSing() {
		return getInt("sing");
	}

}
