package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxInstypeField<M extends BaseMxInstypeField<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTypeID(java.lang.Integer typeID) {
		set("typeID", typeID);
	}
	
	public java.lang.Integer getTypeID() {
		return getInt("typeID");
	}

	public void setFieldID(java.lang.Integer fieldID) {
		set("fieldID", fieldID);
	}
	
	public java.lang.Integer getFieldID() {
		return getInt("fieldID");
	}

	public void setFieldNum(java.lang.String fieldNum) {
		set("fieldNum", fieldNum);
	}
	
	public java.lang.String getFieldNum() {
		return getStr("fieldNum");
	}

	public void setIsStart(java.lang.Integer isStart) {
		set("isStart", isStart);
	}
	
	public java.lang.Integer getIsStart() {
		return getInt("isStart");
	}

}
