package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxRoleMenu<M extends BaseMxRoleMenu<M>> extends Model<M> implements IBean {

	public void setRmId(java.lang.Integer rmId) {
		set("rmId", rmId);
	}
	
	public java.lang.Integer getRmId() {
		return getInt("rmId");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public void setMenuId(java.lang.Integer menuId) {
		set("menuId", menuId);
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menuId");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
