package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxIlogLastdayresult<M extends BaseMxIlogLastdayresult<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setInsID(java.lang.Integer insID) {
		set("insID", insID);
	}
	
	public java.lang.Integer getInsID() {
		return getInt("insID");
	}

	public void setIlogDay(java.util.Date ilogDay) {
		set("ilogDay", ilogDay);
	}
	
	public java.util.Date getIlogDay() {
		return get("ilogDay");
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		set("serial_number", serialNumber);
	}
	
	public java.lang.String getSerialNumber() {
		return getStr("serial_number");
	}

	public void setIpAddress(java.lang.String ipAddress) {
		set("ip_address", ipAddress);
	}
	
	public java.lang.String getIpAddress() {
		return getStr("ip_address");
	}

	public void setIlogidPastnumber(java.lang.Integer ilogidPastnumber) {
		set("ilogID_pastNumber", ilogidPastnumber);
	}
	
	public java.lang.Integer getIlogidPastnumber() {
		return getInt("ilogID_pastNumber");
	}

	public void setIlogidLastnumber(java.lang.Integer ilogidLastnumber) {
		set("ilogID_lastNumber", ilogidLastnumber);
	}
	
	public java.lang.Integer getIlogidLastnumber() {
		return getInt("ilogID_lastNumber");
	}

	public void setReportType(java.lang.String reportType) {
		set("reportType", reportType);
	}
	
	public java.lang.String getReportType() {
		return getStr("reportType");
	}

	public void setTotalImpressionsTotal(java.lang.Integer totalImpressionsTotal) {
		set("total_impressions_total", totalImpressionsTotal);
	}
	
	public java.lang.Integer getTotalImpressionsTotal() {
		return getInt("total_impressions_total");
	}

	public void setPrintedSidedSheetsTwoTotal(java.lang.Integer printedSidedSheetsTwoTotal) {
		set("printed_sided_sheets_two_total", printedSidedSheetsTwoTotal);
	}
	
	public java.lang.Integer getPrintedSidedSheetsTwoTotal() {
		return getInt("printed_sided_sheets_two_total");
	}

	public void setColorPrintedImpressionsTotal(java.lang.Integer colorPrintedImpressionsTotal) {
		set("color_printed_impressions_total", colorPrintedImpressionsTotal);
	}
	
	public java.lang.Integer getColorPrintedImpressionsTotal() {
		return getInt("color_printed_impressions_total");
	}

	public void setBlackPrintedImpressionsTotal(java.lang.Integer blackPrintedImpressionsTotal) {
		set("black_printed_impressions_total", blackPrintedImpressionsTotal);
	}
	
	public java.lang.Integer getBlackPrintedImpressionsTotal() {
		return getInt("black_printed_impressions_total");
	}

	public void setColorCopiedImpressionsTotal(java.lang.Integer colorCopiedImpressionsTotal) {
		set("color_copied_impressions_total", colorCopiedImpressionsTotal);
	}
	
	public java.lang.Integer getColorCopiedImpressionsTotal() {
		return getInt("color_copied_impressions_total");
	}

	public void setBlackCopiedImpressionsTotal(java.lang.Integer blackCopiedImpressionsTotal) {
		set("black_copied_impressions_total", blackCopiedImpressionsTotal);
	}
	
	public java.lang.Integer getBlackCopiedImpressionsTotal() {
		return getInt("black_copied_impressions_total");
	}

	public void setColorCopiedLargeSheetsTotal(java.lang.Integer colorCopiedLargeSheetsTotal) {
		set("color_copied_large_sheets_total", colorCopiedLargeSheetsTotal);
	}
	
	public java.lang.Integer getColorCopiedLargeSheetsTotal() {
		return getInt("color_copied_large_sheets_total");
	}

	public void setBlackCopiedLargeSheetsTotal(java.lang.Integer blackCopiedLargeSheetsTotal) {
		set("black_copied_large_sheets_total", blackCopiedLargeSheetsTotal);
	}
	
	public java.lang.Integer getBlackCopiedLargeSheetsTotal() {
		return getInt("black_copied_large_sheets_total");
	}

	public void setColorPrintedLargeSheetsTotal(java.lang.Integer colorPrintedLargeSheetsTotal) {
		set("color_printed_large_sheets_total", colorPrintedLargeSheetsTotal);
	}
	
	public java.lang.Integer getColorPrintedLargeSheetsTotal() {
		return getInt("color_printed_large_sheets_total");
	}

	public void setBlackPrintedLargeSheetsTotal(java.lang.Integer blackPrintedLargeSheetsTotal) {
		set("black_printed_large_sheets_total", blackPrintedLargeSheetsTotal);
	}
	
	public java.lang.Integer getBlackPrintedLargeSheetsTotal() {
		return getInt("black_printed_large_sheets_total");
	}

	public void setColorPrintedSidedSheetsTwoTotal(java.lang.Integer colorPrintedSidedSheetsTwoTotal) {
		set("color_printed_sided_sheets_two_total", colorPrintedSidedSheetsTwoTotal);
	}
	
	public java.lang.Integer getColorPrintedSidedSheetsTwoTotal() {
		return getInt("color_printed_sided_sheets_two_total");
	}

	public void setBlackPrintedSidedSheetsTwoTotal(java.lang.Integer blackPrintedSidedSheetsTwoTotal) {
		set("black_printed_sided_sheets_two_total", blackPrintedSidedSheetsTwoTotal);
	}
	
	public java.lang.Integer getBlackPrintedSidedSheetsTwoTotal() {
		return getInt("black_printed_sided_sheets_two_total");
	}

	public void setColorCopiedSidedSheetsTwoTotal(java.lang.Integer colorCopiedSidedSheetsTwoTotal) {
		set("color_copied_sided_sheets_two_total", colorCopiedSidedSheetsTwoTotal);
	}
	
	public java.lang.Integer getColorCopiedSidedSheetsTwoTotal() {
		return getInt("color_copied_sided_sheets_two_total");
	}

	public void setBlackCopiedSidedSheetsTwoTotal(java.lang.Integer blackCopiedSidedSheetsTwoTotal) {
		set("black_copied_sided_sheets_two_total", blackCopiedSidedSheetsTwoTotal);
	}
	
	public java.lang.Integer getBlackCopiedSidedSheetsTwoTotal() {
		return getInt("black_copied_sided_sheets_two_total");
	}

	public void setSidedSheetsTwoTotal(java.lang.Integer sidedSheetsTwoTotal) {
		set("sided_sheets_two_total", sidedSheetsTwoTotal);
	}
	
	public java.lang.Integer getSidedSheetsTwoTotal() {
		return getInt("sided_sheets_two_total");
	}

	public void setFaxImpressionsTotal(java.lang.Integer faxImpressionsTotal) {
		set("fax_impressions_total", faxImpressionsTotal);
	}
	
	public java.lang.Integer getFaxImpressionsTotal() {
		return getInt("fax_impressions_total");
	}

	public void setMeter1Total(java.lang.Integer meter1Total) {
		set("meter1_total", meter1Total);
	}
	
	public java.lang.Integer getMeter1Total() {
		return getInt("meter1_total");
	}

	public void setMeter2Total(java.lang.Integer meter2Total) {
		set("meter2_total", meter2Total);
	}
	
	public java.lang.Integer getMeter2Total() {
		return getInt("meter2_total");
	}

	public void setMeter3Total(java.lang.Integer meter3Total) {
		set("meter3_total", meter3Total);
	}
	
	public java.lang.Integer getMeter3Total() {
		return getInt("meter3_total");
	}

	public void setMeter4Total(java.lang.Integer meter4Total) {
		set("meter4_total", meter4Total);
	}
	
	public java.lang.Integer getMeter4Total() {
		return getInt("meter4_total");
	}

}
