package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxUnit<M extends BaseMxUnit<M>> extends Model<M> implements IBean {

	public void setUnitID(java.lang.Integer unitID) {
		set("unitID", unitID);
	}
	
	public java.lang.Integer getUnitID() {
		return getInt("unitID");
	}

	public void setUnitName(java.lang.String unitName) {
		set("unitName", unitName);
	}
	
	public java.lang.String getUnitName() {
		return getStr("unitName");
	}

	public void setClientID(java.lang.Integer clientID) {
		set("clientID", clientID);
	}
	
	public java.lang.Integer getClientID() {
		return getInt("clientID");
	}

	public void setCityID(java.lang.Integer cityID) {
		set("cityID", cityID);
	}
	
	public java.lang.Integer getCityID() {
		return getInt("cityID");
	}

	public void setProvID(java.lang.Integer provID) {
		set("provID", provID);
	}
	
	public java.lang.Integer getProvID() {
		return getInt("provID");
	}

	public void setAreaID(java.lang.Integer areaID) {
		set("areaID", areaID);
	}
	
	public java.lang.Integer getAreaID() {
		return getInt("areaID");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setUnitStatus(java.lang.Integer unitStatus) {
		set("unitStatus", unitStatus);
	}
	
	public java.lang.Integer getUnitStatus() {
		return getInt("unitStatus");
	}

}
