package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLigentOrg<M extends BaseLigentOrg<M>> extends Model<M> implements IBean {

	public void setOrgID(java.lang.Integer orgID) {
		set("orgID", orgID);
	}
	
	public java.lang.Integer getOrgID() {
		return getInt("orgID");
	}

	public void setOrgName(java.lang.String orgName) {
		set("orgName", orgName);
	}
	
	public java.lang.String getOrgName() {
		return getStr("orgName");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}
	
	public java.lang.String getKeyword() {
		return getStr("keyword");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setOrgStatus(java.lang.Integer orgStatus) {
		set("orgStatus", orgStatus);
	}
	
	public java.lang.Integer getOrgStatus() {
		return getInt("orgStatus");
	}

}
