package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxPoint<M extends BaseMxPoint<M>> extends Model<M> implements IBean {

	public void setPointID(java.lang.Integer pointID) {
		set("pointID", pointID);
	}
	
	public java.lang.Integer getPointID() {
		return getInt("pointID");
	}

	public void setPointName(java.lang.String pointName) {
		set("pointName", pointName);
	}
	
	public java.lang.String getPointName() {
		return getStr("pointName");
	}

	public void setLng(java.lang.Double lng) {
		set("lng", lng);
	}
	
	public java.lang.Double getLng() {
		return getDouble("lng");
	}

	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}
	
	public java.lang.Double getLat() {
		return getDouble("lat");
	}

	public void setPtype(java.lang.Integer ptype) {
		set("ptype", ptype);
	}
	
	public java.lang.Integer getPtype() {
		return getInt("ptype");
	}

	public void setUserID(java.lang.Integer userID) {
		set("userID", userID);
	}
	
	public java.lang.Integer getUserID() {
		return getInt("userID");
	}

	public void setClientID(java.lang.Integer clientID) {
		set("clientID", clientID);
	}
	
	public java.lang.Integer getClientID() {
		return getInt("clientID");
	}

	public void setUnitID(java.lang.Integer unitID) {
		set("unitID", unitID);
	}
	
	public java.lang.Integer getUnitID() {
		return getInt("unitID");
	}

	public void setAreaID(java.lang.Integer areaID) {
		set("areaID", areaID);
	}
	
	public java.lang.Integer getAreaID() {
		return getInt("areaID");
	}

	public void setProvID(java.lang.Integer provID) {
		set("provID", provID);
	}
	
	public java.lang.Integer getProvID() {
		return getInt("provID");
	}

	public void setCityID(java.lang.Integer cityID) {
		set("cityID", cityID);
	}
	
	public java.lang.Integer getCityID() {
		return getInt("cityID");
	}

	public void setLinkName(java.lang.String linkName) {
		set("linkName", linkName);
	}
	
	public java.lang.String getLinkName() {
		return getStr("linkName");
	}

	public void setLinkPhone(java.lang.String linkPhone) {
		set("linkPhone", linkPhone);
	}
	
	public java.lang.String getLinkPhone() {
		return getStr("linkPhone");
	}

	public void setLinkMail(java.lang.String linkMail) {
		set("linkMail", linkMail);
	}
	
	public java.lang.String getLinkMail() {
		return getStr("linkMail");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setApic(java.lang.String apic) {
		set("apic", apic);
	}
	
	public java.lang.String getApic() {
		return getStr("apic");
	}

	public void setBpic(java.lang.String bpic) {
		set("bpic", bpic);
	}
	
	public java.lang.String getBpic() {
		return getStr("bpic");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

}
