package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxMsg<M extends BaseMxMsg<M>> extends Model<M> implements IBean {

	public void setMsgID(java.lang.Integer msgID) {
		set("msgID", msgID);
	}
	
	public java.lang.Integer getMsgID() {
		return getInt("msgID");
	}

	public void setMsgContent(java.lang.String msgContent) {
		set("msgContent", msgContent);
	}
	
	public java.lang.String getMsgContent() {
		return getStr("msgContent");
	}

	public void setMsgtype(java.lang.String msgtype) {
		set("msgtype", msgtype);
	}
	
	public java.lang.String getMsgtype() {
		return getStr("msgtype");
	}

	public void setMsgSendTime(java.util.Date msgSendTime) {
		set("msgSendTime", msgSendTime);
	}
	
	public java.util.Date getMsgSendTime() {
		return get("msgSendTime");
	}

	public void setMsgSenderID(java.lang.Integer msgSenderID) {
		set("msgSenderID", msgSenderID);
	}
	
	public java.lang.Integer getMsgSenderID() {
		return getInt("msgSenderID");
	}

	public void setMsgGetterID(java.lang.Integer msgGetterID) {
		set("msgGetterID", msgGetterID);
	}
	
	public java.lang.Integer getMsgGetterID() {
		return getInt("msgGetterID");
	}

	public void setMsgGetTime(java.util.Date msgGetTime) {
		set("msgGetTime", msgGetTime);
	}
	
	public java.util.Date getMsgGetTime() {
		return get("msgGetTime");
	}

	public void setMsgStatus(java.lang.Integer msgStatus) {
		set("msgStatus", msgStatus);
	}
	
	public java.lang.Integer getMsgStatus() {
		return getInt("msgStatus");
	}

	public void setMsgforID(java.lang.Integer msgforID) {
		set("msgforID", msgforID);
	}
	
	public java.lang.Integer getMsgforID() {
		return getInt("msgforID");
	}

}
