package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLigentDep<M extends BaseLigentDep<M>> extends Model<M> implements IBean {

	public void setDepID(java.lang.Integer depID) {
		set("depID", depID);
	}
	
	public java.lang.Integer getDepID() {
		return getInt("depID");
	}

	public void setDepName(java.lang.String depName) {
		set("depName", depName);
	}
	
	public java.lang.String getDepName() {
		return getStr("depName");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}
	
	public java.lang.String getKeyword() {
		return getStr("keyword");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setDepStatus(java.lang.Integer depStatus) {
		set("depStatus", depStatus);
	}
	
	public java.lang.Integer getDepStatus() {
		return getInt("depStatus");
	}

}
