package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxInstype<M extends BaseMxInstype<M>> extends Model<M> implements IBean {

	public void setTypeID(java.lang.Integer typeID) {
		set("typeID", typeID);
	}
	
	public java.lang.Integer getTypeID() {
		return getInt("typeID");
	}

	public void setTypeName(java.lang.String typeName) {
		set("typeName", typeName);
	}
	
	public java.lang.String getTypeName() {
		return getStr("typeName");
	}

	public void setTypeNote(java.lang.Integer typeNote) {
		set("typeNote", typeNote);
	}
	
	public java.lang.Integer getTypeNote() {
		return getInt("typeNote");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

}
