package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxWarnuser<M extends BaseMxWarnuser<M>> extends Model<M> implements IBean {

	public void setUserWarnId(java.lang.Integer userWarnId) {
		set("userWarnId", userWarnId);
	}
	
	public java.lang.Integer getUserWarnId() {
		return getInt("userWarnId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setWarnTypeId(java.lang.String warnTypeId) {
		set("warnTypeId", warnTypeId);
	}
	
	public java.lang.String getWarnTypeId() {
		return getStr("warnTypeId");
	}

	public void setWarnEmail(java.lang.String warnEmail) {
		set("warnEmail", warnEmail);
	}
	
	public java.lang.String getWarnEmail() {
		return getStr("warnEmail");
	}

	public void setTonerCapacity(java.lang.Double tonerCapacity) {
		set("tonerCapacity", tonerCapacity);
	}
	
	public java.lang.Double getTonerCapacity() {
		return getDouble("tonerCapacity");
	}

}
