package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLigentUser<M extends BaseLigentUser<M>> extends Model<M> implements IBean {

	public void setUserID(java.lang.Integer userID) {
		set("userID", userID);
	}
	
	public java.lang.Integer getUserID() {
		return getInt("userID");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public void setUserFirstName(java.lang.String userFirstName) {
		set("userFirstName", userFirstName);
	}
	
	public java.lang.String getUserFirstName() {
		return getStr("userFirstName");
	}

	public void setUserSecondName(java.lang.String userSecondName) {
		set("userSecondName", userSecondName);
	}
	
	public java.lang.String getUserSecondName() {
		return getStr("userSecondName");
	}

	public void setUserAccount(java.lang.String userAccount) {
		set("userAccount", userAccount);
	}
	
	public java.lang.String getUserAccount() {
		return getStr("userAccount");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("userPwd", userPwd);
	}
	
	public java.lang.String getUserPwd() {
		return getStr("userPwd");
	}

	public void setUserAge(java.lang.Integer userAge) {
		set("userAge", userAge);
	}
	
	public java.lang.Integer getUserAge() {
		return getInt("userAge");
	}

	public void setUserSex(java.lang.Integer userSex) {
		set("userSex", userSex);
	}
	
	public java.lang.Integer getUserSex() {
		return getInt("userSex");
	}

	public void setUserPhone(java.lang.String userPhone) {
		set("userPhone", userPhone);
	}
	
	public java.lang.String getUserPhone() {
		return getStr("userPhone");
	}

	public void setUserRole(java.lang.Integer userRole) {
		set("userRole", userRole);
	}
	
	public java.lang.Integer getUserRole() {
		return getInt("userRole");
	}

	public void setClientID(java.lang.Integer clientID) {
		set("clientID", clientID);
	}
	
	public java.lang.Integer getClientID() {
		return getInt("clientID");
	}

	public void setUnitID(java.lang.Integer unitID) {
		set("unitID", unitID);
	}
	
	public java.lang.Integer getUnitID() {
		return getInt("unitID");
	}

	public void setPointID(java.lang.Integer pointID) {
		set("pointID", pointID);
	}
	
	public java.lang.Integer getPointID() {
		return getInt("pointID");
	}

	public void setUserOrg(java.lang.Integer userOrg) {
		set("userOrg", userOrg);
	}
	
	public java.lang.Integer getUserOrg() {
		return getInt("userOrg");
	}

	public void setUserDep(java.lang.Integer userDep) {
		set("userDep", userDep);
	}
	
	public java.lang.Integer getUserDep() {
		return getInt("userDep");
	}

	public void setGuruID(java.lang.Integer guruID) {
		set("guruID", guruID);
	}
	
	public java.lang.Integer getGuruID() {
		return getInt("guruID");
	}

	public void setUserUnit(java.lang.String userUnit) {
		set("userUnit", userUnit);
	}
	
	public java.lang.String getUserUnit() {
		return getStr("userUnit");
	}

	public void setUserArea(java.lang.Integer userArea) {
		set("userArea", userArea);
	}
	
	public java.lang.Integer getUserArea() {
		return getInt("userArea");
	}

	public void setUserMail(java.lang.String userMail) {
		set("userMail", userMail);
	}
	
	public java.lang.String getUserMail() {
		return getStr("userMail");
	}

	public void setUserIdCard(java.lang.String userIdCard) {
		set("userIdCard", userIdCard);
	}
	
	public java.lang.String getUserIdCard() {
		return getStr("userIdCard");
	}

	public void setUserPicPath(java.lang.String userPicPath) {
		set("userPicPath", userPicPath);
	}
	
	public java.lang.String getUserPicPath() {
		return getStr("userPicPath");
	}

	public void setCrTime(java.util.Date crTime) {
		set("crTime", crTime);
	}
	
	public java.util.Date getCrTime() {
		return get("crTime");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setUserStatus(java.lang.Integer userStatus) {
		set("userStatus", userStatus);
	}
	
	public java.lang.Integer getUserStatus() {
		return getInt("userStatus");
	}

}
