package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxIlogLastdaypertime<M extends BaseMxIlogLastdaypertime<M>> extends Model<M> implements IBean {

	public void setMilID(java.lang.Integer milID) {
		set("milID", milID);
	}
	
	public java.lang.Integer getMilID() {
		return getInt("milID");
	}

	public void setIlogID(java.lang.Integer ilogID) {
		set("ilogID", ilogID);
	}
	
	public java.lang.Integer getIlogID() {
		return getInt("ilogID");
	}

	public void setInsID(java.lang.Integer insID) {
		set("insID", insID);
	}
	
	public java.lang.Integer getInsID() {
		return getInt("insID");
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		set("serial_number", serialNumber);
	}
	
	public java.lang.String getSerialNumber() {
		return getStr("serial_number");
	}

	public void setIlogTime(java.util.Date ilogTime) {
		set("ilogTime", ilogTime);
	}
	
	public java.util.Date getIlogTime() {
		return get("ilogTime");
	}

}
