package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxPtype<M extends BaseMxPtype<M>> extends Model<M> implements IBean {

	public void setPID(java.lang.Integer pID) {
		set("pID", pID);
	}
	
	public java.lang.Integer getPID() {
		return getInt("pID");
	}

	public void setPname(java.lang.String pname) {
		set("pname", pname);
	}
	
	public java.lang.String getPname() {
		return getStr("pname");
	}

}
