package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLigentRole<M extends BaseLigentRole<M>> extends Model<M> implements IBean {

	public void setRoleID(java.lang.Integer roleID) {
		set("roleID", roleID);
	}
	
	public java.lang.Integer getRoleID() {
		return getInt("roleID");
	}

	public void setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
	}
	
	public java.lang.String getRoleName() {
		return getStr("roleName");
	}

	public void setChilds(java.lang.String childs) {
		set("childs", childs);
	}
	
	public java.lang.String getChilds() {
		return getStr("childs");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setRoleStatus(java.lang.Integer roleStatus) {
		set("roleStatus", roleStatus);
	}
	
	public java.lang.Integer getRoleStatus() {
		return getInt("roleStatus");
	}

	public void setRoleSing(java.lang.String roleSing) {
		set("roleSing", roleSing);
	}
	
	public java.lang.String getRoleSing() {
		return getStr("roleSing");
	}

}
