package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxEmergency<M extends BaseMxEmergency<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setEngemergency(java.lang.String engemergency) {
		set("engemergency", engemergency);
	}
	
	public java.lang.String getEngemergency() {
		return getStr("engemergency");
	}

	public void setChineemergency(java.lang.String chineemergency) {
		set("chineemergency", chineemergency);
	}
	
	public java.lang.String getChineemergency() {
		return getStr("chineemergency");
	}

}
