package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxApilog<M extends BaseMxApilog<M>> extends Model<M> implements IBean {

	public void setLogID(java.lang.Integer logID) {
		set("logID", logID);
	}
	
	public java.lang.Integer getLogID() {
		return getInt("logID");
	}

	public void setAskUrl(java.lang.String askUrl) {
		set("askUrl", askUrl);
	}
	
	public java.lang.String getAskUrl() {
		return getStr("askUrl");
	}

	public void setAskJson(java.lang.String askJson) {
		set("askJson", askJson);
	}
	
	public java.lang.String getAskJson() {
		return getStr("askJson");
	}

	public void setResultCode(java.lang.Integer resultCode) {
		set("resultCode", resultCode);
	}
	
	public java.lang.Integer getResultCode() {
		return getInt("resultCode");
	}

	public void setSuccessMsg(java.lang.String successMsg) {
		set("successMsg", successMsg);
	}
	
	public java.lang.String getSuccessMsg() {
		return getStr("successMsg");
	}

	public void setErrorMsg(java.lang.String errorMsg) {
		set("errorMsg", errorMsg);
	}
	
	public java.lang.String getErrorMsg() {
		return getStr("errorMsg");
	}

	public void setLogTime(java.util.Date logTime) {
		set("logTime", logTime);
	}
	
	public java.util.Date getLogTime() {
		return get("logTime");
	}

	public void setIlogID(java.lang.Integer ilogID) {
		set("ilogID", ilogID);
	}
	
	public java.lang.Integer getIlogID() {
		return getInt("ilogID");
	}

}
