package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxIlogLastdaypermonth<M extends BaseMxIlogLastdaypermonth<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setInsID(java.lang.Integer insID) {
		set("insID", insID);
	}
	
	public java.lang.Integer getInsID() {
		return getInt("insID");
	}

	public void setIlogID(java.lang.Integer ilogID) {
		set("ilogID", ilogID);
	}
	
	public java.lang.Integer getIlogID() {
		return getInt("ilogID");
	}

	public void setFkID(java.lang.Integer fkID) {
		set("fkID", fkID);
	}
	
	public java.lang.Integer getFkID() {
		return getInt("fkID");
	}

	public void setIlogflag(java.lang.Integer ilogflag) {
		set("ilogflag", ilogflag);
	}
	
	public java.lang.Integer getIlogflag() {
		return getInt("ilogflag");
	}

	public void setIlogMonth(java.lang.String ilogMonth) {
		set("ilogMonth", ilogMonth);
	}
	
	public java.lang.String getIlogMonth() {
		return getStr("ilogMonth");
	}

	public void setTotalImpressions(java.lang.Integer totalImpressions) {
		set("total_impressions", totalImpressions);
	}
	
	public java.lang.Integer getTotalImpressions() {
		return getInt("total_impressions");
	}

	public void setPrintedSidedSheetsTwo(java.lang.Integer printedSidedSheetsTwo) {
		set("printed_sided_sheets_two", printedSidedSheetsTwo);
	}
	
	public java.lang.Integer getPrintedSidedSheetsTwo() {
		return getInt("printed_sided_sheets_two");
	}

	public void setColorPrintedImpressions(java.lang.Integer colorPrintedImpressions) {
		set("color_printed_impressions", colorPrintedImpressions);
	}
	
	public java.lang.Integer getColorPrintedImpressions() {
		return getInt("color_printed_impressions");
	}

	public void setBlackPrintedImpressions(java.lang.Integer blackPrintedImpressions) {
		set("black_printed_impressions", blackPrintedImpressions);
	}
	
	public java.lang.Integer getBlackPrintedImpressions() {
		return getInt("black_printed_impressions");
	}

	public void setColorCopiedImpressions(java.lang.Integer colorCopiedImpressions) {
		set("color_copied_impressions", colorCopiedImpressions);
	}
	
	public java.lang.Integer getColorCopiedImpressions() {
		return getInt("color_copied_impressions");
	}

	public void setBlackCopiedImpressions(java.lang.Integer blackCopiedImpressions) {
		set("black_copied_impressions", blackCopiedImpressions);
	}
	
	public java.lang.Integer getBlackCopiedImpressions() {
		return getInt("black_copied_impressions");
	}

	public void setColorCopiedLargeSheets(java.lang.Integer colorCopiedLargeSheets) {
		set("color_copied_large_sheets", colorCopiedLargeSheets);
	}
	
	public java.lang.Integer getColorCopiedLargeSheets() {
		return getInt("color_copied_large_sheets");
	}

	public void setBlackCopiedLargeSheets(java.lang.Integer blackCopiedLargeSheets) {
		set("black_copied_large_sheets", blackCopiedLargeSheets);
	}
	
	public java.lang.Integer getBlackCopiedLargeSheets() {
		return getInt("black_copied_large_sheets");
	}

	public void setColorPrintedLargeSheets(java.lang.Integer colorPrintedLargeSheets) {
		set("color_printed_large_sheets", colorPrintedLargeSheets);
	}
	
	public java.lang.Integer getColorPrintedLargeSheets() {
		return getInt("color_printed_large_sheets");
	}

	public void setBlackPrintedLargeSheets(java.lang.Integer blackPrintedLargeSheets) {
		set("black_printed_large_sheets", blackPrintedLargeSheets);
	}
	
	public java.lang.Integer getBlackPrintedLargeSheets() {
		return getInt("black_printed_large_sheets");
	}

	public void setColorPrintedSidedSheetsTwo(java.lang.Integer colorPrintedSidedSheetsTwo) {
		set("color_printed_sided_sheets_two", colorPrintedSidedSheetsTwo);
	}
	
	public java.lang.Integer getColorPrintedSidedSheetsTwo() {
		return getInt("color_printed_sided_sheets_two");
	}

	public void setBlackPrintedSidedSheetsTwo(java.lang.Integer blackPrintedSidedSheetsTwo) {
		set("black_printed_sided_sheets_two", blackPrintedSidedSheetsTwo);
	}
	
	public java.lang.Integer getBlackPrintedSidedSheetsTwo() {
		return getInt("black_printed_sided_sheets_two");
	}

	public void setColorCopiedSidedSheetsTwo(java.lang.Integer colorCopiedSidedSheetsTwo) {
		set("color_copied_sided_sheets_two", colorCopiedSidedSheetsTwo);
	}
	
	public java.lang.Integer getColorCopiedSidedSheetsTwo() {
		return getInt("color_copied_sided_sheets_two");
	}

	public void setBlackCopiedSidedSheetsTwo(java.lang.Integer blackCopiedSidedSheetsTwo) {
		set("black_copied_sided_sheets_two", blackCopiedSidedSheetsTwo);
	}
	
	public java.lang.Integer getBlackCopiedSidedSheetsTwo() {
		return getInt("black_copied_sided_sheets_two");
	}

	public void setSidedSheetsTwo(java.lang.Integer sidedSheetsTwo) {
		set("sided_sheets_two", sidedSheetsTwo);
	}
	
	public java.lang.Integer getSidedSheetsTwo() {
		return getInt("sided_sheets_two");
	}

	public void setFaxImpressions(java.lang.Integer faxImpressions) {
		set("fax_impressions", faxImpressions);
	}
	
	public java.lang.Integer getFaxImpressions() {
		return getInt("fax_impressions");
	}

	public void setMeter1(java.lang.Integer meter1) {
		set("meter1", meter1);
	}
	
	public java.lang.Integer getMeter1() {
		return getInt("meter1");
	}

	public void setMeter2(java.lang.Integer meter2) {
		set("meter2", meter2);
	}
	
	public java.lang.Integer getMeter2() {
		return getInt("meter2");
	}

	public void setMeter3(java.lang.Integer meter3) {
		set("meter3", meter3);
	}
	
	public java.lang.Integer getMeter3() {
		return getInt("meter3");
	}

	public void setMeter4(java.lang.Integer meter4) {
		set("meter4", meter4);
	}
	
	public java.lang.Integer getMeter4() {
		return getInt("meter4");
	}

	public void setBlackTonerMaxCapacity(java.lang.Integer blackTonerMaxCapacity) {
		set("black_toner_max_capacity", blackTonerMaxCapacity);
	}
	
	public java.lang.Integer getBlackTonerMaxCapacity() {
		return getInt("black_toner_max_capacity");
	}

	public void setBlackTonerActualCapacity(java.lang.Integer blackTonerActualCapacity) {
		set("black_toner_actual_capacity", blackTonerActualCapacity);
	}
	
	public java.lang.Integer getBlackTonerActualCapacity() {
		return getInt("black_toner_actual_capacity");
	}

	public void setYellowTonerMaxCapacity(java.lang.Integer yellowTonerMaxCapacity) {
		set("yellow_toner_max_capacity", yellowTonerMaxCapacity);
	}
	
	public java.lang.Integer getYellowTonerMaxCapacity() {
		return getInt("yellow_toner_max_capacity");
	}

	public void setYellowTonerActualCapacity(java.lang.Integer yellowTonerActualCapacity) {
		set("yellow_toner_actual_capacity", yellowTonerActualCapacity);
	}
	
	public java.lang.Integer getYellowTonerActualCapacity() {
		return getInt("yellow_toner_actual_capacity");
	}

	public void setMagentaTonerMaxCapacity(java.lang.Integer magentaTonerMaxCapacity) {
		set("magenta_toner_max_capacity", magentaTonerMaxCapacity);
	}
	
	public java.lang.Integer getMagentaTonerMaxCapacity() {
		return getInt("magenta_toner_max_capacity");
	}

	public void setMagentaTonerActualCapacity(java.lang.Integer magentaTonerActualCapacity) {
		set("magenta_toner_actual_capacity", magentaTonerActualCapacity);
	}
	
	public java.lang.Integer getMagentaTonerActualCapacity() {
		return getInt("magenta_toner_actual_capacity");
	}

	public void setCyanTonerMaxCapacity(java.lang.Integer cyanTonerMaxCapacity) {
		set("cyan_toner_max_capacity", cyanTonerMaxCapacity);
	}
	
	public java.lang.Integer getCyanTonerMaxCapacity() {
		return getInt("cyan_toner_max_capacity");
	}

	public void setCyanTonerActualCapacity(java.lang.Integer cyanTonerActualCapacity) {
		set("cyan_toner_actual_capacity", cyanTonerActualCapacity);
	}
	
	public java.lang.Integer getCyanTonerActualCapacity() {
		return getInt("cyan_toner_actual_capacity");
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		set("serial_number", serialNumber);
	}
	
	public java.lang.String getSerialNumber() {
		return getStr("serial_number");
	}

	public void setMacAddress(java.lang.String macAddress) {
		set("mac_address", macAddress);
	}
	
	public java.lang.String getMacAddress() {
		return getStr("mac_address");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setSystemName(java.lang.String systemName) {
		set("system_name", systemName);
	}
	
	public java.lang.String getSystemName() {
		return getStr("system_name");
	}

	public void setIpAddress(java.lang.String ipAddress) {
		set("ip_address", ipAddress);
	}
	
	public java.lang.String getIpAddress() {
		return getStr("ip_address");
	}

}
