package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxInstrumentlog2016<M extends BaseMxInstrumentlog2016<M>> extends Model<M> implements IBean {

	public void setIlogID(java.lang.Integer ilogID) {
		set("ilogID", ilogID);
	}
	
	public java.lang.Integer getIlogID() {
		return getInt("ilogID");
	}

	public void setInsID(java.lang.Integer insID) {
		set("insID", insID);
	}
	
	public java.lang.Integer getInsID() {
		return getInt("insID");
	}

	public void setIlogType(java.lang.Integer ilogType) {
		set("ilogType", ilogType);
	}
	
	public java.lang.Integer getIlogType() {
		return getInt("ilogType");
	}

	public void setIlogNode(java.lang.String ilogNode) {
		set("ilogNode", ilogNode);
	}
	
	public java.lang.String getIlogNode() {
		return getStr("ilogNode");
	}

	public void setIlogTime(java.util.Date ilogTime) {
		set("ilogTime", ilogTime);
	}
	
	public java.util.Date getIlogTime() {
		return get("ilogTime");
	}

	public void setIlogValue(java.lang.String ilogValue) {
		set("ilogValue", ilogValue);
	}
	
	public java.lang.String getIlogValue() {
		return getStr("ilogValue");
	}

	public void setIlogDesc(java.lang.String ilogDesc) {
		set("ilogDesc", ilogDesc);
	}
	
	public java.lang.String getIlogDesc() {
		return getStr("ilogDesc");
	}

	public void setCrtime(java.util.Date crtime) {
		set("crtime", crtime);
	}
	
	public java.util.Date getCrtime() {
		return get("crtime");
	}

	public void setFlagtime(java.lang.Long flagtime) {
		set("flagtime", flagtime);
	}
	
	public java.lang.Long getFlagtime() {
		return getLong("flagtime");
	}

	public void setInkingSum(java.lang.Integer inkingSum) {
		set("inkingSum", inkingSum);
	}
	
	public java.lang.Integer getInkingSum() {
		return getInt("inkingSum");
	}

	public void setColorPrintedImpressions(java.lang.Integer colorPrintedImpressions) {
		set("color_printed_impressions", colorPrintedImpressions);
	}
	
	public java.lang.Integer getColorPrintedImpressions() {
		return getInt("color_printed_impressions");
	}

	public void setBlackPrintedImpressions(java.lang.Integer blackPrintedImpressions) {
		set("black_printed_impressions", blackPrintedImpressions);
	}
	
	public java.lang.Integer getBlackPrintedImpressions() {
		return getInt("black_printed_impressions");
	}

	public void setColorCopiedImpressions(java.lang.Integer colorCopiedImpressions) {
		set("color_copied_impressions", colorCopiedImpressions);
	}
	
	public java.lang.Integer getColorCopiedImpressions() {
		return getInt("color_copied_impressions");
	}

	public void setBlackCopiedImpressions(java.lang.Integer blackCopiedImpressions) {
		set("black_copied_impressions", blackCopiedImpressions);
	}
	
	public java.lang.Integer getBlackCopiedImpressions() {
		return getInt("black_copied_impressions");
	}

	public void setPrintedTwoSidedSheets(java.lang.Integer printedTwoSidedSheets) {
		set("printed_two_sided_sheets", printedTwoSidedSheets);
	}
	
	public java.lang.Integer getPrintedTwoSidedSheets() {
		return getInt("printed_two_sided_sheets");
	}

	public void setColorPrintedLargeSheets(java.lang.Integer colorPrintedLargeSheets) {
		set("color_printed_large_sheets", colorPrintedLargeSheets);
	}
	
	public java.lang.Integer getColorPrintedLargeSheets() {
		return getInt("color_printed_large_sheets");
	}

	public void setBlackPrintedLargeSheets(java.lang.Integer blackPrintedLargeSheets) {
		set("black_printed_large_sheets", blackPrintedLargeSheets);
	}
	
	public java.lang.Integer getBlackPrintedLargeSheets() {
		return getInt("black_printed_large_sheets");
	}

	public void setColorPrintedTwoSidedSheets(java.lang.Integer colorPrintedTwoSidedSheets) {
		set("color_printed_two_sided_sheets", colorPrintedTwoSidedSheets);
	}
	
	public java.lang.Integer getColorPrintedTwoSidedSheets() {
		return getInt("color_printed_two_sided_sheets");
	}

	public void setBlackPrintedTwoSidedSheets(java.lang.Integer blackPrintedTwoSidedSheets) {
		set("black_printed_two_sided_sheets", blackPrintedTwoSidedSheets);
	}
	
	public java.lang.Integer getBlackPrintedTwoSidedSheets() {
		return getInt("black_printed_two_sided_sheets");
	}

	public void setColorCopiedLargeSheets(java.lang.Integer colorCopiedLargeSheets) {
		set("color_copied_large_sheets", colorCopiedLargeSheets);
	}
	
	public java.lang.Integer getColorCopiedLargeSheets() {
		return getInt("color_copied_large_sheets");
	}

	public void setBlackCopiedLargeSheets(java.lang.Integer blackCopiedLargeSheets) {
		set("black_copied_large_sheets", blackCopiedLargeSheets);
	}
	
	public java.lang.Integer getBlackCopiedLargeSheets() {
		return getInt("black_copied_large_sheets");
	}

	public void setColorCopiedTwoSidedSheets(java.lang.Integer colorCopiedTwoSidedSheets) {
		set("color_copied_two_sided_sheets", colorCopiedTwoSidedSheets);
	}
	
	public java.lang.Integer getColorCopiedTwoSidedSheets() {
		return getInt("color_copied_two_sided_sheets");
	}

	public void setBlackCopiedTwoSidedSheets(java.lang.Integer blackCopiedTwoSidedSheets) {
		set("black_copied_two_sided_sheets", blackCopiedTwoSidedSheets);
	}
	
	public java.lang.Integer getBlackCopiedTwoSidedSheets() {
		return getInt("black_copied_two_sided_sheets");
	}

}
