package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxFiliale<M extends BaseMxFiliale<M>> extends Model<M> implements IBean {

	public void setFID(java.lang.Integer fID) {
		set("fID", fID);
	}
	
	public java.lang.Integer getFID() {
		return getInt("fID");
	}

	public void setFName(java.lang.String fName) {
		set("fName", fName);
	}
	
	public java.lang.String getFName() {
		return getStr("fName");
	}

	public void setFStatus(java.lang.Integer fStatus) {
		set("fStatus", fStatus);
	}
	
	public java.lang.Integer getFStatus() {
		return getInt("fStatus");
	}

}
