package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLigentActionRole<M extends BaseLigentActionRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setActionID(java.lang.Integer actionID) {
		set("actionID", actionID);
	}
	
	public java.lang.Integer getActionID() {
		return getInt("actionID");
	}

	public void setRoleID(java.lang.Integer roleID) {
		set("roleID", roleID);
	}
	
	public java.lang.Integer getRoleID() {
		return getInt("roleID");
	}

	public void setRestrict1(java.lang.String restrict1) {
		set("restrict1", restrict1);
	}
	
	public java.lang.String getRestrict1() {
		return getStr("restrict1");
	}

	public void setRestrict2(java.lang.String restrict2) {
		set("restrict2", restrict2);
	}
	
	public java.lang.String getRestrict2() {
		return getStr("restrict2");
	}

	public void setRestrict3(java.lang.String restrict3) {
		set("restrict3", restrict3);
	}
	
	public java.lang.String getRestrict3() {
		return getStr("restrict3");
	}

}
