package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxWarntype<M extends BaseMxWarntype<M>> extends Model<M> implements IBean {

	public void setWarnTypeId(java.lang.Integer warnTypeId) {
		set("warnTypeId", warnTypeId);
	}
	
	public java.lang.Integer getWarnTypeId() {
		return getInt("warnTypeId");
	}

	public void setTypeName(java.lang.String typeName) {
		set("typeName", typeName);
	}
	
	public java.lang.String getTypeName() {
		return getStr("typeName");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
